# Generated by Django 4.2.9 on 2024-03-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_date_alter_customer_technologies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField()),
                ('stu_class', models.CharField(max_length=23)),
            ],
        ),
    ]
